name: Pre-merge checks

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Download deps
        run: npm install

      - name: Run tests
        run: npm run test
